/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "/home/ayush/vsdflow/verilog/spi_slave.v:6" *)
module spi_slave(SCK, SDI, CSB, SDO, sdoenb, idata_0_, idata_1_, idata_2_, idata_3_, idata_4_, idata_5_, idata_6_, idata_7_, odata_0_, odata_1_, odata_2_, odata_3_, odata_4_, odata_5_, odata_6_, odata_7_, oaddr_0_, oaddr_1_, oaddr_2_, oaddr_3_, oaddr_4_, oaddr_5_, oaddr_6_, oaddr_7_, rdstb, wrstb);
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _000_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _001_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _002_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _003_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _004_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _005_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _006_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _007_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _008_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _009_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _010_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _011_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _012_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _013_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:38" *)
  wire _014_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:38" *)
  wire _015_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:38" *)
  wire _016_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:38" *)
  wire _017_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:38" *)
  wire _018_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:38" *)
  wire _019_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:38" *)
  wire _020_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:38" *)
  wire _021_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _022_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _023_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _024_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _025_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _026_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _027_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _028_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _029_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _030_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  wire _031_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:38" *)
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:9" *)
  input CSB;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:7" *)
  input SCK;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:8" *)
  input SDI;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:10" *)
  output SDO;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:18" *)
  wire addr_0_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:18" *)
  wire addr_1_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:18" *)
  wire addr_2_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:18" *)
  wire addr_3_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:18" *)
  wire addr_4_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:18" *)
  wire addr_5_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:18" *)
  wire addr_6_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:18" *)
  wire addr_7_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:23" *)
  wire count_0_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:23" *)
  wire count_1_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:23" *)
  wire count_2_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:26" *)
  wire fixed_0_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:26" *)
  wire fixed_1_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:26" *)
  wire fixed_2_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:12" *)
  input idata_0_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:12" *)
  input idata_1_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:12" *)
  input idata_2_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:12" *)
  input idata_3_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:12" *)
  input idata_4_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:12" *)
  input idata_5_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:12" *)
  input idata_6_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:12" *)
  input idata_7_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:30" *)
  wire ldata_0_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:30" *)
  wire ldata_1_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:30" *)
  wire ldata_2_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:30" *)
  wire ldata_3_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:30" *)
  wire ldata_4_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:30" *)
  wire ldata_5_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:30" *)
  wire ldata_6_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:14" *)
  output oaddr_0_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:14" *)
  output oaddr_1_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:14" *)
  output oaddr_2_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:14" *)
  output oaddr_3_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:14" *)
  output oaddr_4_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:14" *)
  output oaddr_5_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:14" *)
  output oaddr_6_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:14" *)
  output oaddr_7_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:13" *)
  output odata_0_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:13" *)
  output odata_1_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:13" *)
  output odata_2_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:13" *)
  output odata_3_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:13" *)
  output odata_4_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:13" *)
  output odata_5_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:13" *)
  output odata_6_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:13" *)
  output odata_7_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:15" *)
  output rdstb;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:25" *)
  wire readmode;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:11" *)
  output sdoenb;
  wire state_0_;
  wire state_1_;
  wire state_2_;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:24" *)
  wire writemode;
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:16" *)
  output wrstb;
  sky130_fd_sc_hd__clkinv_1 _162_ (
    .A(state_2_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__clkinv_1 _163_ (
    .A(fixed_2_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__clkinv_1 _164_ (
    .A(state_0_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__clkinv_1 _165_ (
    .A(addr_2_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__clkinv_1 _166_ (
    .A(addr_3_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__clkinv_1 _167_ (
    .A(addr_4_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__clkinv_1 _168_ (
    .A(addr_5_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__clkinv_1 _169_ (
    .A(addr_6_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__clkinv_1 _170_ (
    .A(_036_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__clkinv_1 _171_ (
    .A(CSB),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand3_1 _172_ (
    .A(count_0_),
    .B(count_1_),
    .C(count_2_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nor2_1 _173_ (
    .A(_138_),
    .B(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nor2_1 _174_ (
    .A(fixed_2_),
    .B(fixed_1_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nor3b_1 _175_ (
    .A(fixed_2_),
    .B(fixed_1_),
    .C_N(fixed_0_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _176_ (
    .A(fixed_0_),
    .B(_044_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor2_1 _177_ (
    .A(_042_),
    .B(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__o21ai_0 _178_ (
    .A1(_042_),
    .A2(_046_),
    .B1(state_1_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__o21ai_0 _179_ (
    .A1(_138_),
    .A2(_042_),
    .B1(_048_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__a22o_1 _180_ (
    .A1(state_0_),
    .A2(_042_),
    .B1(_047_),
    .B2(state_1_),
    .X(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _181_ (
    .A(state_2_),
    .B(_042_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__o21ai_0 _182_ (
    .A1(_140_),
    .A2(_042_),
    .B1(_049_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nor2_1 _183_ (
    .A(state_2_),
    .B(addr_0_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nor2_1 _184_ (
    .A(_138_),
    .B(SDI),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor2_1 _185_ (
    .A(_050_),
    .B(_051_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nand2_1 _186_ (
    .A(_138_),
    .B(addr_1_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _187_ (
    .A(state_2_),
    .B(addr_0_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _188_ (
    .A(_052_),
    .B(_053_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nand2_1 _189_ (
    .A(state_2_),
    .B(addr_1_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__o21ai_0 _190_ (
    .A1(state_2_),
    .A2(_141_),
    .B1(_054_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nand2_1 _191_ (
    .A(state_2_),
    .B(addr_2_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__o21ai_0 _192_ (
    .A1(state_2_),
    .A2(_142_),
    .B1(_055_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nand2_1 _193_ (
    .A(state_2_),
    .B(addr_3_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__o21ai_0 _194_ (
    .A1(state_2_),
    .A2(_039_),
    .B1(_056_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nor2_1 _195_ (
    .A(state_2_),
    .B(_040_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__a21o_1 _196_ (
    .A1(state_2_),
    .A2(addr_4_),
    .B1(_057_),
    .X(_149_)
  );
  sky130_fd_sc_hd__nand2_1 _197_ (
    .A(state_2_),
    .B(addr_5_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__o21ai_0 _198_ (
    .A1(state_2_),
    .A2(_041_),
    .B1(_058_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nand2_1 _199_ (
    .A(_138_),
    .B(addr_7_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor2_1 _200_ (
    .A(_138_),
    .B(_041_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__o21ai_0 _201_ (
    .A1(_138_),
    .A2(_041_),
    .B1(_059_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__and2_0 _202_ (
    .A(state_1_),
    .B(readmode),
    .X(_038_)
  );
  sky130_fd_sc_hd__nor2_1 _203_ (
    .A(count_1_),
    .B(count_2_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor3_1 _204_ (
    .A(count_0_),
    .B(count_1_),
    .C(count_2_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__or3_1 _205_ (
    .A(count_0_),
    .B(count_1_),
    .C(count_2_),
    .X(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _206_ (
    .A(idata_0_),
    .B(_062_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor2_1 _207_ (
    .A(ldata_0_),
    .B(_038_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__a21oi_1 _208_ (
    .A1(_038_),
    .A2(_064_),
    .B1(_065_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _209_ (
    .A(ldata_0_),
    .B(_063_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _210_ (
    .A(idata_1_),
    .B(_062_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nor2_1 _211_ (
    .A(ldata_1_),
    .B(_038_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__a31oi_1 _212_ (
    .A1(_038_),
    .A2(_066_),
    .A3(_067_),
    .B1(_068_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _213_ (
    .A(ldata_1_),
    .B(_063_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _214_ (
    .A(idata_2_),
    .B(_062_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor2_1 _215_ (
    .A(ldata_2_),
    .B(_038_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__a31oi_1 _216_ (
    .A1(_038_),
    .A2(_069_),
    .A3(_070_),
    .B1(_071_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _217_ (
    .A(ldata_2_),
    .B(_063_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand2_1 _218_ (
    .A(idata_3_),
    .B(_062_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nor2_1 _219_ (
    .A(ldata_3_),
    .B(_038_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__a31oi_1 _220_ (
    .A1(_038_),
    .A2(_072_),
    .A3(_073_),
    .B1(_074_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _221_ (
    .A(ldata_3_),
    .B(_063_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand2_1 _222_ (
    .A(idata_4_),
    .B(_062_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nor2_1 _223_ (
    .A(ldata_4_),
    .B(_038_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__a31oi_1 _224_ (
    .A1(_038_),
    .A2(_075_),
    .A3(_076_),
    .B1(_077_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _225_ (
    .A(ldata_4_),
    .B(_063_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _226_ (
    .A(idata_5_),
    .B(_062_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor2_1 _227_ (
    .A(ldata_5_),
    .B(_038_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__a31oi_1 _228_ (
    .A1(_038_),
    .A2(_078_),
    .A3(_079_),
    .B1(_080_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _229_ (
    .A(ldata_5_),
    .B(_063_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nand2_1 _230_ (
    .A(idata_6_),
    .B(_062_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nor2_1 _231_ (
    .A(ldata_6_),
    .B(_038_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__a31oi_1 _232_ (
    .A1(_038_),
    .A2(_081_),
    .A3(_082_),
    .B1(_083_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _233_ (
    .A(ldata_6_),
    .B(_063_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand2_1 _234_ (
    .A(idata_7_),
    .B(_062_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nor2_1 _235_ (
    .A(_143_),
    .B(_038_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__a31oi_1 _236_ (
    .A1(_038_),
    .A2(_084_),
    .A3(_085_),
    .B1(_086_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__o21ai_0 _237_ (
    .A1(readmode),
    .A2(_159_),
    .B1(_043_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand2_1 _238_ (
    .A(state_1_),
    .B(_042_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand3_1 _239_ (
    .A(_138_),
    .B(_159_),
    .C(_088_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__a21oi_1 _240_ (
    .A1(_087_),
    .A2(_089_),
    .B1(state_0_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand4_1 _241_ (
    .A(state_1_),
    .B(count_0_),
    .C(count_1_),
    .D(count_2_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nor2_1 _242_ (
    .A(_045_),
    .B(_090_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__a31oi_1 _243_ (
    .A1(_138_),
    .A2(addr_0_),
    .A3(_091_),
    .B1(_051_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor2_1 _244_ (
    .A(state_2_),
    .B(_091_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nor2_1 _245_ (
    .A(state_0_),
    .B(_093_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__o22a_1 _246_ (
    .A1(state_0_),
    .A2(_092_),
    .B1(_094_),
    .B2(addr_0_),
    .X(_000_)
  );
  sky130_fd_sc_hd__nand3_1 _247_ (
    .A(addr_0_),
    .B(_052_),
    .C(_091_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__a21oi_1 _248_ (
    .A1(addr_0_),
    .A2(_091_),
    .B1(_052_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__a21oi_1 _249_ (
    .A1(state_2_),
    .A2(addr_0_),
    .B1(_096_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nor2_1 _250_ (
    .A(_140_),
    .B(addr_1_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__a31oi_1 _251_ (
    .A1(_140_),
    .A2(_095_),
    .A3(_097_),
    .B1(_098_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _252_ (
    .A(addr_0_),
    .B(addr_1_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__a31oi_1 _253_ (
    .A1(addr_0_),
    .A2(addr_1_),
    .A3(_091_),
    .B1(addr_2_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor4_1 _254_ (
    .A(_141_),
    .B(_045_),
    .C(_090_),
    .D(_099_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__o311a_1 _255_ (
    .A1(state_2_),
    .A2(_100_),
    .A3(_101_),
    .B1(_140_),
    .C1(_054_),
    .X(_102_)
  );
  sky130_fd_sc_hd__a21oi_1 _256_ (
    .A1(state_0_),
    .A2(_141_),
    .B1(_102_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__xnor2_1 _257_ (
    .A(addr_3_),
    .B(_101_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__o21ai_0 _258_ (
    .A1(state_2_),
    .A2(_103_),
    .B1(_055_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__mux2_1 _259_ (
    .A0(addr_3_),
    .A1(_104_),
    .S(_140_),
    .X(_003_)
  );
  sky130_fd_sc_hd__and3_1 _260_ (
    .A(addr_3_),
    .B(addr_4_),
    .C(_101_),
    .X(_105_)
  );
  sky130_fd_sc_hd__a21oi_1 _261_ (
    .A1(addr_3_),
    .A2(_101_),
    .B1(addr_4_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__o31ai_1 _262_ (
    .A1(state_2_),
    .A2(_105_),
    .A3(_106_),
    .B1(_056_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__mux2_1 _263_ (
    .A0(addr_4_),
    .A1(_107_),
    .S(_140_),
    .X(_004_)
  );
  sky130_fd_sc_hd__nor2_1 _264_ (
    .A(_149_),
    .B(_105_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a21o_1 _265_ (
    .A1(_057_),
    .A2(_105_),
    .B1(state_0_),
    .X(_109_)
  );
  sky130_fd_sc_hd__o22ai_1 _266_ (
    .A1(_140_),
    .A2(_040_),
    .B1(_108_),
    .B2(_109_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__a41oi_1 _267_ (
    .A1(addr_3_),
    .A2(addr_4_),
    .A3(_057_),
    .A4(_101_),
    .B1(addr_6_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__a311oi_1 _268_ (
    .A1(addr_5_),
    .A2(addr_6_),
    .A3(_105_),
    .B1(_110_),
    .C1(_060_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nand2_1 _269_ (
    .A(_140_),
    .B(_058_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _270_ (
    .A1_N(_111_),
    .A2_N(_112_),
    .B1(state_0_),
    .B2(_041_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand2_1 _271_ (
    .A(state_0_),
    .B(addr_7_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__a31oi_1 _272_ (
    .A1(addr_5_),
    .A2(addr_6_),
    .A3(_105_),
    .B1(_151_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nor4b_1 _273_ (
    .A(_040_),
    .B(_041_),
    .C(_059_),
    .D_N(_105_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__o31ai_1 _274_ (
    .A1(state_0_),
    .A2(_114_),
    .A3(_115_),
    .B1(_113_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor3_1 _275_ (
    .A(state_1_),
    .B(state_2_),
    .C(state_0_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nand2b_1 _276_ (
    .A_N(_116_),
    .B(count_0_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__xnor2_1 _277_ (
    .A(count_0_),
    .B(_116_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand3b_1 _278_ (
    .A_N(_116_),
    .B(count_1_),
    .C(count_0_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__xnor2_1 _279_ (
    .A(count_1_),
    .B(_117_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__xnor2_1 _280_ (
    .A(count_2_),
    .B(_118_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _281_ (
    .A(state_0_),
    .B(_062_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__mux2_1 _282_ (
    .A0(SDI),
    .A1(writemode),
    .S(_119_),
    .X(_031_)
  );
  sky130_fd_sc_hd__nand3_1 _283_ (
    .A(count_0_),
    .B(state_0_),
    .C(_061_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__mux2_1 _284_ (
    .A0(SDI),
    .A1(readmode),
    .S(_120_),
    .X(_030_)
  );
  sky130_fd_sc_hd__o21ai_0 _285_ (
    .A1(count_0_),
    .A2(count_1_),
    .B1(count_2_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nor2b_1 _286_ (
    .A(_061_),
    .B_N(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__o21ai_0 _287_ (
    .A1(count_1_),
    .A2(count_2_),
    .B1(_121_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nor2_1 _288_ (
    .A(SDI),
    .B(_123_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__o21ai_0 _289_ (
    .A1(fixed_0_),
    .A2(_122_),
    .B1(state_0_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nand2b_1 _290_ (
    .A_N(state_2_),
    .B(state_1_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nor3_1 _291_ (
    .A(_042_),
    .B(_044_),
    .C(_126_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__xnor2_1 _292_ (
    .A(fixed_0_),
    .B(_127_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__o22ai_1 _293_ (
    .A1(_124_),
    .A2(_125_),
    .B1(_128_),
    .B2(state_0_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nor2_1 _294_ (
    .A(state_0_),
    .B(_126_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__o41ai_1 _295_ (
    .A1(fixed_0_),
    .A2(state_0_),
    .A3(_042_),
    .A4(_126_),
    .B1(fixed_1_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__a21oi_1 _296_ (
    .A1(state_0_),
    .A2(_122_),
    .B1(_130_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand3_1 _297_ (
    .A(fixed_0_),
    .B(state_0_),
    .C(_122_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nor4_1 _298_ (
    .A(fixed_1_),
    .B(fixed_0_),
    .C(_042_),
    .D(_126_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a31oi_1 _299_ (
    .A1(fixed_2_),
    .A2(_140_),
    .A3(_133_),
    .B1(_131_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nand2_1 _300_ (
    .A(_132_),
    .B(_134_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nor2_1 _301_ (
    .A(fixed_1_),
    .B(_123_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__o21ai_0 _302_ (
    .A1(fixed_2_),
    .A2(_122_),
    .B1(state_0_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__o32ai_1 _303_ (
    .A1(_139_),
    .A2(state_0_),
    .A3(_133_),
    .B1(_135_),
    .B2(_136_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _304_ (
    .A0(_152_),
    .A1(SDI),
    .S(_129_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _305_ (
    .A0(_153_),
    .A1(_152_),
    .S(_129_),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _306_ (
    .A0(_154_),
    .A1(_153_),
    .S(_129_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _307_ (
    .A0(_155_),
    .A1(_154_),
    .S(_129_),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _308_ (
    .A0(_156_),
    .A1(_155_),
    .S(_129_),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux2_1 _309_ (
    .A0(_157_),
    .A1(_156_),
    .S(_129_),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _310_ (
    .A0(_158_),
    .A1(_157_),
    .S(_129_),
    .X(_028_)
  );
  sky130_fd_sc_hd__nor2_1 _311_ (
    .A(writemode),
    .B(_161_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nor2_1 _312_ (
    .A(_090_),
    .B(_137_),
    .Y(_032_)
  );
  (* keep = 32'd1 *)
  BUFX2 _313_ (
    .A(_143_),
    .Y(SDO)
  );
  (* keep = 32'd1 *)
  BUFX2 _314_ (
    .A(_144_),
    .Y(oaddr_0_)
  );
  (* keep = 32'd1 *)
  BUFX2 _315_ (
    .A(_145_),
    .Y(oaddr_1_)
  );
  (* keep = 32'd1 *)
  BUFX2 _316_ (
    .A(_146_),
    .Y(oaddr_2_)
  );
  (* keep = 32'd1 *)
  BUFX2 _317_ (
    .A(_147_),
    .Y(oaddr_3_)
  );
  (* keep = 32'd1 *)
  BUFX2 _318_ (
    .A(_148_),
    .Y(oaddr_4_)
  );
  (* keep = 32'd1 *)
  BUFX2 _319_ (
    .A(_149_),
    .Y(oaddr_5_)
  );
  (* keep = 32'd1 *)
  BUFX2 _320_ (
    .A(_150_),
    .Y(oaddr_6_)
  );
  (* keep = 32'd1 *)
  BUFX2 _321_ (
    .A(_151_),
    .Y(oaddr_7_)
  );
  (* keep = 32'd1 *)
  BUFX2 _322_ (
    .A(SDI),
    .Y(odata_0_)
  );
  (* keep = 32'd1 *)
  BUFX2 _323_ (
    .A(_152_),
    .Y(odata_1_)
  );
  (* keep = 32'd1 *)
  BUFX2 _324_ (
    .A(_153_),
    .Y(odata_2_)
  );
  (* keep = 32'd1 *)
  BUFX2 _325_ (
    .A(_154_),
    .Y(odata_3_)
  );
  (* keep = 32'd1 *)
  BUFX2 _326_ (
    .A(_155_),
    .Y(odata_4_)
  );
  (* keep = 32'd1 *)
  BUFX2 _327_ (
    .A(_156_),
    .Y(odata_5_)
  );
  (* keep = 32'd1 *)
  BUFX2 _328_ (
    .A(_157_),
    .Y(odata_6_)
  );
  (* keep = 32'd1 *)
  BUFX2 _329_ (
    .A(_158_),
    .Y(odata_7_)
  );
  (* keep = 32'd1 *)
  BUFX2 _330_ (
    .A(_159_),
    .Y(rdstb)
  );
  (* keep = 32'd1 *)
  BUFX2 _331_ (
    .A(_160_),
    .Y(sdoenb)
  );
  (* keep = 32'd1 *)
  BUFX2 _332_ (
    .A(_161_),
    .Y(wrstb)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:38" *)
  sky130_fd_sc_hd__dfrtn_1 _333_ (
    .CLK_N(SCK),
    .D(_014_),
    .Q(ldata_0_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:38" *)
  sky130_fd_sc_hd__dfrtn_1 _334_ (
    .CLK_N(SCK),
    .D(_015_),
    .Q(ldata_1_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:38" *)
  sky130_fd_sc_hd__dfrtn_1 _335_ (
    .CLK_N(SCK),
    .D(_016_),
    .Q(ldata_2_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:38" *)
  sky130_fd_sc_hd__dfrtn_1 _336_ (
    .CLK_N(SCK),
    .D(_017_),
    .Q(ldata_3_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:38" *)
  sky130_fd_sc_hd__dfrtn_1 _337_ (
    .CLK_N(SCK),
    .D(_018_),
    .Q(ldata_4_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:38" *)
  sky130_fd_sc_hd__dfrtn_1 _338_ (
    .CLK_N(SCK),
    .D(_019_),
    .Q(ldata_5_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:38" *)
  sky130_fd_sc_hd__dfrtn_1 _339_ (
    .CLK_N(SCK),
    .D(_020_),
    .Q(ldata_6_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:38" *)
  sky130_fd_sc_hd__dfrtn_1 _340_ (
    .CLK_N(SCK),
    .D(_021_),
    .Q(_143_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:38" *)
  sky130_fd_sc_hd__dfrtn_1 _341_ (
    .CLK_N(SCK),
    .D(_032_),
    .Q(_161_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:38" *)
  sky130_fd_sc_hd__dfrtn_1 _342_ (
    .CLK_N(SCK),
    .D(_038_),
    .Q(_036_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _343_ (
    .CLK(SCK),
    .D(_022_),
    .Q(_152_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _344_ (
    .CLK(SCK),
    .D(_023_),
    .Q(_153_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _345_ (
    .CLK(SCK),
    .D(_024_),
    .Q(_154_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _346_ (
    .CLK(SCK),
    .D(_025_),
    .Q(_155_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _347_ (
    .CLK(SCK),
    .D(_026_),
    .Q(_156_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _348_ (
    .CLK(SCK),
    .D(_027_),
    .Q(_157_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _349_ (
    .CLK(SCK),
    .D(_028_),
    .Q(_158_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _350_ (
    .CLK(SCK),
    .D(_011_),
    .Q(fixed_0_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _351_ (
    .CLK(SCK),
    .D(_012_),
    .Q(fixed_1_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _352_ (
    .CLK(SCK),
    .D(_013_),
    .Q(fixed_2_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _353_ (
    .CLK(SCK),
    .D(_030_),
    .Q(readmode),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _354_ (
    .CLK(SCK),
    .D(_031_),
    .Q(writemode),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _355_ (
    .CLK(SCK),
    .D(_008_),
    .Q(count_0_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _356_ (
    .CLK(SCK),
    .D(_009_),
    .Q(count_1_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _357_ (
    .CLK(SCK),
    .D(_010_),
    .Q(count_2_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _358_ (
    .CLK(SCK),
    .D(_000_),
    .Q(addr_0_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _359_ (
    .CLK(SCK),
    .D(_001_),
    .Q(addr_1_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _360_ (
    .CLK(SCK),
    .D(_002_),
    .Q(addr_2_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _361_ (
    .CLK(SCK),
    .D(_003_),
    .Q(addr_3_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _362_ (
    .CLK(SCK),
    .D(_004_),
    .Q(addr_4_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _363_ (
    .CLK(SCK),
    .D(_005_),
    .Q(addr_5_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _364_ (
    .CLK(SCK),
    .D(_006_),
    .Q(addr_6_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _365_ (
    .CLK(SCK),
    .D(_007_),
    .Q(addr_7_),
    .RESET_B(_037_)
  );
  (* src = "/home/ayush/vsdflow/verilog/spi_slave.v:77" *)
  sky130_fd_sc_hd__dfrtp_1 _366_ (
    .CLK(SCK),
    .D(_029_),
    .Q(_159_),
    .RESET_B(_037_)
  );
  sky130_fd_sc_hd__dfstp_2 _367_ (
    .CLK(SCK),
    .D(_033_),
    .Q(state_0_),
    .SET_B(_037_)
  );
  sky130_fd_sc_hd__dfrtp_1 _368_ (
    .CLK(SCK),
    .D(_034_),
    .Q(state_1_),
    .RESET_B(_037_)
  );
  sky130_fd_sc_hd__dfrtp_1 _369_ (
    .CLK(SCK),
    .D(_035_),
    .Q(state_2_),
    .RESET_B(_037_)
  );
endmodule
