
create_clock -name SCK -period 2 -waveform {0 1} [get_ports SCK]
set_input_transition -rise -min 1 -clock SCK [get_ports SCK]
set_input_transition -fall -min 1 -clock SCK [get_ports SCK]
set_input_transition -rise -max 1 -clock SCK [get_ports SCK]
set_input_transition -fall -max 1 -clock SCK [get_ports SCK]
set_input_delay  -min -rise 1 -clock SCK [get_ports SCK]
set_input_delay  -min -fall 1 -clock SCK [get_ports SCK]
set_input_delay  -max -rise 1 -clock SCK [get_ports SCK]
set_input_delay  -max -fall 1 -clock SCK [get_ports SCK]
set_input_delay -clock  SCK -min -rise  0.5 [get_ports SDI]
set_input_delay -clock  SCK -min -fall  0.5 [get_ports SDI]
set_input_delay -clock  SCK -max -rise  1 [get_ports SDI]
set_input_delay -clock  SCK -max -fall  1 [get_ports SDI]
set_input_transition -clock  SCK -min -rise  0.5 [get_ports SDI]
set_input_transition -clock  SCK -min -fall  0.5 [get_ports SDI]
set_input_transition -clock  SCK -max -rise  1 [get_ports SDI]
set_input_transition -clock  SCK -max -fall  1 [get_ports SDI]
set_input_delay -clock  SCK -min -rise  0.5 [get_ports CSB*]
set_input_delay -clock  SCK -min -fall  0.5 [get_ports CSB*]
set_input_delay -clock  SCK -max -rise  1 [get_ports CSB*]
set_input_delay -clock  SCK -max -fall  1 [get_ports CSB*]
set_input_transition -clock  SCK -min -rise  0.5 [get_ports CSB*]
set_input_transition -clock  SCK -min -fall  0.5 [get_ports CSB*]
set_input_transition -clock  SCK -max -rise  1 [get_ports CSB*]
set_input_transition -clock  SCK -max -fall  1 [get_ports CSB*]
set_input_delay -clock  SCK -min -rise  0.5 [get_ports idata*]
set_input_delay -clock  SCK -min -fall  0.5 [get_ports idata*]
set_input_delay -clock  SCK -max -rise  1 [get_ports idata*]
set_input_delay -clock  SCK -max -fall  1 [get_ports idata*]
set_input_transition -clock  SCK -min -rise  0.5 [get_ports idata*]
set_input_transition -clock  SCK -min -fall  0.5 [get_ports idata*]
set_input_transition -clock  SCK -max -rise  1 [get_ports idata*]
set_input_transition -clock  SCK -max -fall  1 [get_ports idata*]
set_output_delay -clock  SCK -min -rise  0.5 [get_ports SDO]
set_output_delay -clock  SCK -min -fall  0.5 [get_ports SDO]
set_output_delay -clock  SCK -max -rise  1 [get_ports SDO]
set_output_delay -clock  SCK -max -fall  1 [get_ports SDO]
set_load 1 [get_ports SDO]
set_output_delay -clock  SCK -min -rise  0.5 [get_ports sdoenb]
set_output_delay -clock  SCK -min -fall  0.5 [get_ports sdoenb]
set_output_delay -clock  SCK -max -rise  1 [get_ports sdoenb]
set_output_delay -clock  SCK -max -fall  1 [get_ports sdoenb]
set_load 1 [get_ports sdoenb]
set_output_delay -clock  SCK -min -rise  0.5 [get_ports odata*]
set_output_delay -clock  SCK -min -fall  0.5 [get_ports odata*]
set_output_delay -clock  SCK -max -rise  1 [get_ports odata*]
set_output_delay -clock  SCK -max -fall  1 [get_ports odata*]
set_load 1 [get_ports odata*]
set_output_delay -clock  SCK -min -rise  0.5 [get_ports oaddr*]
set_output_delay -clock  SCK -min -fall  0.5 [get_ports oaddr*]
set_output_delay -clock  SCK -max -rise  1 [get_ports oaddr*]
set_output_delay -clock  SCK -max -fall  1 [get_ports oaddr*]
set_load 1 [get_ports oaddr*]
set_output_delay -clock  SCK -min -rise  0.5 [get_ports rdstb]
set_output_delay -clock  SCK -min -fall  0.5 [get_ports rdstb]
set_output_delay -clock  SCK -max -rise  1 [get_ports rdstb]
set_output_delay -clock  SCK -max -fall  1 [get_ports rdstb]
set_load 1 [get_ports rdstb]
set_output_delay -clock  SCK -min -rise  0.5 [get_ports wrstb]
set_output_delay -clock  SCK -min -fall  0.5 [get_ports wrstb]
set_output_delay -clock  SCK -max -rise  1 [get_ports wrstb]
set_output_delay -clock  SCK -max -fall  1 [get_ports wrstb]
set_load 1 [get_ports wrstb]